name: Deploy via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to FTP server
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          ftp-server: ${{ secrets.FTP_SERVER }}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          ftp-port: ${{ secrets.FTP_PORT }}
          local-dir: ./ # Local directory to upload (current directory)
          server-dir: /home/benguetf/metal.ilearnwebtech.com/ # Remote directory
          method: ftp # or ftps for secure FTP
